### ISSUE TITLE
feature-daos-services

### ISSUE THREAD

**Issue by kissthbw** [kissthbw/ShinShin-Back#1]
@MasterOsorio 
Crear en el paquete com.bit.dao las clases DAO del modelo de datos (ver **ProductoDAO.java**)

Crear en el paquete com.bit.service y com.bit.service.impl (**ver ProductoService y ProductoServiceImpl**)

**Comment by MasterOsorio** [comment]
cerrado en commit 6c9be9f107a84e88cdd6589714b3496a7996d228
