### ISSUE TITLE
feature-codigo-random

### ISSUE THREAD

**Issue by kissthbw** [kissthbw/ShinShin-Back#2]
Crear una clase de utilitarias, con un método estático para la generación de números aleatorios, esto es para la funcionalidad del envío de SMS con código de verificación.
Ver https://stackoverflow.com/questions/33577737/how-to-generate-a-random-long-with-4-digits-in-java

**Comment by MasterOsorio** [comment]
Cerrado en commit a96514b3c67618f9b55b1d18bd65e6cd8e06f98f
