### ISSUE TITLE
fix-activacion-usuario

### ISSUE THREAD

**Issue by kissthbw** [kissthbw/ShinShin-Back#4]
Realizar la corrección pertinente en el metodo activarUsuarios de la clase UsuarioServiceImpl, debido a que siempre (ya sea éxito o error) regresa un objeto SimpleResponse con los valores rsp.setMessage("Exitoso");
rsp.setCode(200); 

Setear los valores cuando la validación del código de verificación no coincida a:
rsp.setMessage("Error");
rsp.setCode(500);

**Comment by MasterOsorio** [comment]
Cerrado en commit b735e11ed22c9531b5300263d36035edc513c0af
